
export const odishaLocations: string[] = [
  "Alipurduar",
  "Asansol",
  "Bally",
  "Balurghat",
  "Bankura",
  "Baranagar",
  "Barasat",
  "Bardhaman",
  "Barrackpore",
  "Basirhat",
  "Berhampore",
  "Bhadreswar",
  "Bhatpara",
  "Birbhum",
  "Bishnupur",
  "Bolpur",
  "Bongaon",
  "Canning",
  "Chakdaha",
  "Chandannagar",
  "Contai",
  "Cooch Behar",
  "Dankuni",
  "Darjeeling",
  "Diamond Harbour",
  "Digha",
  "Dinhata",
  "Dum Dum",
  "Durgapur",
  "English Bazar",
  "Habra",
  "Haldia",
  "Hooghly",
  "Howrah",
  "Islampur",
  "Jalpaiguri",
  "Jhargram",
  "Kalimpong",
  "Kalyani",
  "Kanchrapara",
  "Kharagpur",
  "Koch Bihar",
  "Kolkata",
  "Krishnanagar",
  "Kurseong",
  "Madhyamgram",
  "Malda",
  "Medinipur",
  "Midnapore",
  "Murshidabad",
  "Nabadwip",
  "Naihati",
  "New Town",
  "North 24 Parganas",
  "Purba Bardhaman",
  "Purba Medinipur",
  "Purulia",
  "Raiganj",
  "Rampurhat",
  "Ranaghat",
  "Serampore",
  "Siliguri",
  "South 24 Parganas",
  "Suri",
  "Tamluk",
  "Titagarh",
  "Uluberia",
  "Uttar Dinajpur",
];
